name: publish-php-images
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  build_and_push_base_images:
    name: Build PHP base images
    strategy:
      matrix:
        php-version: ['7.4.27', '8.0.14', '8.1.1']
        php-sapi: ['cli', 'fpm', 'apache']
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set environment variables
        run: |
          echo "PHP_VERSION=${{ matrix.php-version }}" >> $GITHUB_ENV
          echo "PHP_MINOR_VERSION=$(echo "${{ matrix.php-version }}" | awk -F. '{print $1"."$2}')" >> $GITHUB_ENV

      - name: check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.php-version }} to ghcr.io
        uses: docker/build-push-action@v2
        with:
          push: true
          file: base/Dockerfile
          build-args: |
              PHP_VERSION=${{ matrix.php-version }}
              PHP_EXTENSION=${{ matrix.php-sapi }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/php-${{ matrix.php-sapi }}/base:${{ env.PHP_MINOR_VERSION }}
            ghcr.io/${{ github.repository_owner }}/php-${{ matrix.php-sapi }}/base:${{ env.PHP_VERSION }}

  build_and_push_ext_images:
    name: Build PHP extension images
    needs: build_and_push_base_images
    strategy:
      matrix:
        php-version: ['7.4.27', '8.0.14', '8.1.1']
        php-ext:
          - amqp
          - apcu
          - ast
          - bcmath
          - bz2
          - calendar
          - csv
          - dba
          - decimal
          - ds
          - enchant
          - ev
          - event
          - excimer
          - exif
          - ffi
          - gd
          - geospatial
          - gettext
          - gmagick
          - gmp
          - gnupg
          - grpc
          - http
          - igbinary
          - imagick
          - imap
          - inotify
          - intl
          - json_post
          - ldap
          - lzf
          - mailparse
          - maxminddb
          - mbstring
          - mcrypt
          - memcache
          - memcached
          - mongodb
          - msgpack
          - mysqli
          - odbc
          - opcache
          - opencensus
          - openswoole
          - parallel
          - pcntl
          - pcov
          - pdo_firebird
          - pdo_mysql
          - pdo_oci
          - pdo_pgsql
          - protobuf
          - pspell
          - rdkafka
          - recode
          - redis
          - seaslog
          - shmop
          - snmp
          - snuffleupagus
          - soap
          - solr
          - ssh2
          - swoole
          - sysvmsg
          - sysvsem
          - sysvshm
          - tidy
          - timezonedb
          - uopz
          - uploadprogress
          - uuid
          - vips
          - xdebug
          - xhprof
          - xlswriter
          - xmldiff
          - yac
          - yaml
          - yar
          - zephir_parser
          - zip
          - zmq
          - zookeeper
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

      - name: Set environment variables
        run: |
          echo "PHP_VERSION=${{ matrix.php-version }}" >> $GITHUB_ENV
          echo "PHP_MINOR_VERSION=$(echo "${{ matrix.php-version }}" | awk -F. '{print $1"."$2}')" >> $GITHUB_ENV

      - name: check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.php-version }}-${{ matrix.php-ext }} to ghcr.io
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          file: ext/Dockerfile
          build-args: |
            PHP_VERSION=${{ matrix.php-version }}
            PHP_EXTENSION=${{ matrix.php-ext }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/php-cli/ext:${{ env.PHP_VERSION }}-${{ matrix.php-ext }}
            ghcr.io/${{ github.repository_owner }}/php-cli/ext-${{ matrix.php-ext }}:${{ env.PHP_VERSION }}
            ghcr.io/${{ github.repository_owner }}/php-cli/ext:${{ env.PHP_MINOR_VERSION }}-${{ matrix.php-ext }}
            ghcr.io/${{ github.repository_owner }}/php-cli/ext-${{ matrix.php-ext }}:${{ env.PHP_MINOR_VERSION }}

